spring.application.name=labelinventory

# Database connection settings
spring.datasource.url=jdbc:mysql://localhost:3306/labelinventory
spring.datasource.username=labels
spring.datasource.password=admin

# Specify the DBMS
spring.jpa.database = MYSQL

# Show or not log for each sql query
spring.jpa.show-sql = true

# Hibernate ddl auto (create, create-drop, update)
spring.jpa.hibernate.ddl-auto = update

#spring.security.user.name = admin
#spring.security.user.password = admin